apiVersion: v1
kind: Service
metadata:
  name: react-ui-service
spec:
  selector:
    app: react-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # Optional: Use this if you want to expose the React app on a specific port on the Node
